### ISSUE TITLE
Unable to read taxonomy terms - REST API error in console

### ISSUE THREAD

**Issue by nym1k** [helgatheviking/Radio-Buttons-for-Taxonomies#101]
It seems that when I'm editing a page where I'm using this plugin, it's unable to pull through the current taxonomy terms available as there is an error in the console:

my-site.local/wp-json/wp/v2/media_type?per_page=-1&orderby=name&order=asc&_fields=id%2Cname%2Cparent&_locale=user
`{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): per_page",
  "data": {
    "status": 400,
    "params": {
      "per_page": "per_page must be between 1 (inclusive) and 100 (inclusive)"
    },
    "details": {
      "per_page": {
        "code": "rest_out_of_bounds",
        "message": "per_page must be between 1 (inclusive) and 100 (inclusive)",
        "data": null
      }
    }
  }
}`

It seems that the request is trying to call for an unlimited number of pages, which is causing WordPress to error, and i'm not getting any radio buttons appearing on my posts.

**Comment by helgatheviking** [comment]
Hi Ross. Can you tell me how to reproduce this? You are editing a page in the block editor? Can you confirm this is happening with only the RB4T plugin and a default theme (to rule out any conflicts)?

**Comment by helgatheviking** [comment]
Closing as `wp/v2/media_type` is not a default rest route. And seems like `per_page=-1` is not supported. Re-open if you have more details on how I can reproduce and/or especially how this relates to the Radio Buttons.
