### ISSUE TITLE
Bulk Edit removes terms

### ISSUE THREAD

**Issue by nate-allen** [helgatheviking/Radio-Buttons-for-Taxonomies#105]
If you Bulk Edit custom post types, it deletes any terms that were saved for each post.

To reproduce:

1. Select multiple posts in the post list screen
2. In the Bulk Actions select box choose Edit
3. Change something like the author or status
4. Click Submit

It will remove whatever terms those posts had assigned.

This can be fixed by adding this:

```
// If posts are being bulk edited, we don't want to do anything.
if ( ! empty( $_GET['bulk_edit'] ) ) {
	return $post_id;
}
```

In the first line of the `save_single_term` function in the `class-wordpress-radio-taxonomy.php` file.

**Comment by helgatheviking** [comment]
Hi Nate! Thanks for reporting this. I can't quite reproduce this. I went to Products, bulk edit 3 products and changed their status. the terms for `product_cat` were not wiped out. Anything else you can tell me about how to reproduce? I am not sure we want to entire disable bulk edit saving... though I am just now realizing that the radio input isn't displaying for me on the bulk edit. Was it for you?

**Comment by nate-allen** [comment]
Hi @helgatheviking! I can get it to happen with products on a clean install with just WooCommerce and Radio Buttons for Taxonomies installed. I just made sure I enabled "Product Categories" under Settings > Radio Buttons for Taxonomies. I can see the radio buttons.

It happens when I go to the "Bulk Actions" at the top. Here's a screen capture.

![Kapture 2022-06-16 at 13 19 16](https://user-images.githubusercontent.com/8797898/174130319-a1067702-100b-4052-af35-b7577bca0d4e.gif)

You can see the product category is "Cool Stuff" at the start, but "Uncategorized" at the end.

**Comment by nate-allen** [comment]
@helgatheviking, have you had any luck reproducing this issue on your end? You mentioned "radio input isn't displaying" so I'm wondering if maybe you didn't have "Product Categories" enabled in the plugin Settings when you tested?

**Comment by helgatheviking** [comment]
been on vacation this week so not gotten to look at this yet

**Comment by nate-allen** [comment]
Okay, no worries! Enjoy your vacation. 🙂

**Comment by helgatheviking** [comment]
Hi Nate... I was able to reproduce this so I will try to give it some energy this week. I think going a step beyond what you've proposed... I should only save in the bulk edit mode _if_ there's an actual value. If you don't enter a field, I see the terms being removed which I agree is not default bulk edit behavior.

**Comment by helgatheviking** [comment]
Hi @nate-allen could you test out https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/pull/107 ?

**Comment by nate-allen** [comment]
Hi @helgatheviking, I tested it out and it works!

![Kapture 2022-06-28 at 10 37 04](https://user-images.githubusercontent.com/8797898/176207197-d770bd92-ded0-4ff7-a772-37733a6b7355.gif)
