### ISSUE TITLE
Add composer file

### ISSUE THREAD

**Issue by AaronHolbrook** [helgatheviking/Radio-Buttons-for-Taxonomies#32]
Would allow using this more as a library and including within other projects

**Comment by helgatheviking** [comment]
High Aaron. Thanks for the PR. I'm not super familiar with composer yet. Would there be any kind of future maintenance required on my end? If not, I'm happy to merge it into the git repo, though I'd leave it out of the WP repo.

**Comment by AaronHolbrook** [comment]
Nope, that's it!

**Comment by helgatheviking** [comment]
Ok, great. Can you change 

```
"name": "aaronholbrook/Radio-Buttons-for-Taxonomies"
```

to 

```
"name": "helgatheviking/Radio-Buttons-for-Taxonomies"

```

then I will merge it in.

**Comment by helgatheviking** [comment]
edited and merged! Thanks!
