### ISSUE TITLE
Archive widget cannot be blocked from pages

### ISSUE THREAD

**Issue by rh4789** [helgatheviking/Radio-Buttons-for-Taxonomies#37]
When I try to block the archives widget from pages (dropdown) I get it in list form plus I get the search widget, which I have already blocked separately. 

When I unblock the search widget, the archives are blocked as supposed. 

Thanks Kathy. Great plugin. Rick

**Comment by helgatheviking** [comment]
Rick, I don't understand how this relates to radio buttons for taxonomies. Could you clarify?

**Comment by rh4789** [comment]
OK, wrong area.
