### ISSUE TITLE
Can i use it on a paid plugin?

### ISSUE THREAD

**Issue by pablo-pacheco** [helgatheviking/Radio-Buttons-for-Taxonomies#40]
Hello, can i use your plugin as third party on a paid plugin that i'm developing?

**Comment by helgatheviking** [comment]
Technically, it's GPL so you may do what you wish. I would appreciate proper attribution in the code and if you're going to make money on it a [donation](https://www.youcaring.com/wnt-argentina) would be generous. Good luck.
