### ISSUE TITLE
[Feature] Checkbox VS Radio per content type

### ISSUE THREAD

**Issue by elvismdev** [helgatheviking/Radio-Buttons-for-Taxonomies#41]
Hi Kathy,

I'm running trough this issue ATM, 

Per client requirement, they'll like to have the widget for an specific taxonomy coming out with radio buttons for single selection in content type A, and, at the same time also have it with checkboxes (as default) for multiple selection in content type B. 

I'm looking at the plugin code investigating how to make that possible, if successful with my customization would you be interested in a PR to push it to WP.org as a new feature?

Also I'd like to ask in advance if you have went trough this kind of requirement before, how do you see the feasibility of it and/or some tips where to drive my attention trough your code?

Thanks!

**Comment by elvismdev** [comment]
For instance and reference, I think here's where the extra magic with the content types should happen: https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/blob/master/radio-buttons-for-taxonomies.php#L175-L177

**Comment by helgatheviking** [comment]
You've probably already figured out that this plugin doesn't get much attention from me. Sorry about that. I'd be open to a filter of some kind that you could use to disable the RB4T metabox on certain post types, while still allowing it on others. I'm not sure where that would be added, the code you've referenced wouldn't have access yet to the post type yet. 

I think you'd have to do it in the `WordPress_Radio_Taxonomy` class and possibly in several methods (I think `add_meta_box()`, `remove_meta_box()` and `save_single_term()`. 

I'm not currently inclined to add this myself, so I'm going to close this issue for now.
