### ISSUE TITLE
Dutch translation doesn't work

### ISSUE THREAD

**Issue by gamesaucer** [helgatheviking/Radio-Buttons-for-Taxonomies#45]
When having Wordpress set to Dutch, the translation doesn't load correctly. There seem to be two problems

1. The provided `.mo` file is empty
2. The locale has the incorrect name `nl`. This should be `nl_NL`

**Comment by helgatheviking** [comment]
I'll fix that, but the translations in the plugin folder itself are incomplete and not maintained. You're better off using WordPress' versions from [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/radio-buttons-for-taxonomies/stable/nl/default) and saving them to `wp-content/languages/plugins/radio-buttons-for-taxonomies-nl_NL.mo.` It looks like that translation is missing a few strings, so if you speak Dutch, it would be awesome if you could complete the translation.

**Comment by helgatheviking** [comment]
Closed by ed3cd1e7a85a883c4ebe791d350589c546d86c4c
