### ISSUE TITLE
[dev] Fix odd click behavior

### ISSUE THREAD

**Issue by leymannx** [helgatheviking/Radio-Buttons-for-Taxonomies#51]
I checked out the dev branch for WP5 compatibility and radios appear nicely for the chosen taxonomies.

But odd is, when clicking the radios for the first time, I need to click them twice to actually select them. This only happens when clicking them the first time after document ready.

I'd expect the radios get selected just at the first click.

**Comment by helgatheviking** [comment]
Thanks for the report @leymannx . I'd seen dodgy behavior on clicks some of the time too, but haven't been able to pin it down yet.

**Comment by indextwo** [comment]
I've only taken a super-quick look at this, _but_ I can reproduce it consistently in both latest versions of FF & Chrome under Win10: 

Clicking on the _actual radio button_ `input` results in it not changing, either visually or in its actual state, no matter how many times it's clicked (confirmed by console-logging its `checked` value). Clicking the `label` for said `input` will change it as expected every time.

**Comment by helgatheviking** [comment]
I kinda think a lot of these issues are related to needing to set the state. I was still thinking in PHP that all the form inputs are serialized and submitted to save, but that's not the case in gutenberg.

**Comment by leymannx** [comment]
Also fixed with #53 I'd say.
