### ISSUE TITLE
[dev] All terms get saved instead of just selected terms

### ISSUE THREAD

**Issue by leymannx** [helgatheviking/Radio-Buttons-for-Taxonomies#53]
I checked out the dev branch for WP5 compatibility and radios appear nicely for the chosen taxonomies.

Unfortunately the term saving doesn't seem to work properly. After I selected a term, saved the post and watched it in the frontend, all terms appear.

I'd expect only the chosen term to be applied.

### That's what I selected

![Screenshot 2019-04-10 10 56 20](https://user-images.githubusercontent.com/3585653/55865761-506ff700-5b7f-11e9-9de1-1ad067ce7885.png)

### That's what has been saved

![Screenshot 2019-04-10 10 56 35](https://user-images.githubusercontent.com/3585653/55865793-5e257c80-5b7f-11e9-9d81-3d961d5d2196.png)

**Comment by helgatheviking** [comment]
Great, I was going to open this based on your WP.org reply. And just noticed it myself. I think I have to dig into the API as everything in Gutenberg is saved via the API.

**Comment by helgatheviking** [comment]
Either need to find a way to modify the results of  `WP_REST_Terms_Controller`[https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php] or perhaps extend the class and replace the controller for all radio taxonomies via the `register_taxonomy_args` filter.

**Comment by helgatheviking** [comment]
I actually think this may be more oriented towards the JS side of things. Specifically, may need to mimic how the Radio controls set _state_. https://github.com/WordPress/gutenberg/tree/master/packages/components/src/radio-control

**Comment by helgatheviking** [comment]
@leymannx Hi Norman. I just pushed a few changes. I _think_ it solves the saving issue. I'd appreciate it if you could take a look when you have a chance.

**Comment by leymannx** [comment]
It works super smooth now. Select and updates precisely. Well done!

Only one minor thing with the styles of the focused radio that underlaps the meta box wrapper. It's not bad thing, but it may look broken to the enduser. I'll drop a new issue for that.

**Comment by helgatheviking** [comment]
I've seen the style thing too. Not sure what to do about it. 

Glad it's working! Gotta give credit to @5ally and her work at https://github.com/5ally/my-term-selector/ she's been amazingly helpful on this. 

I am a little nervous about just how _many_ changes were made to the term selector script. I fear it coud be hard to maintain, but we'll cross that bridge when we get to it. 

I'll give a quick thought to the style issue and try to get this packaged up for release!

**Comment by leymannx** [comment]
I'm a little bit concerned regarding backwards compatibility. But you didn't remove any of the old code? So the plugin should still work on older WordPress versions you think?

**Comment by helgatheviking** [comment]
For back compat, the old scripts should still load when not using
Gutenberg.... So anywhere tractional metaboxs are leading. But I only
tested quickly with product post type.
