### ISSUE TITLE
[dev] Can't change selected options when updating post

### ISSUE THREAD

**Issue by leymannx** [helgatheviking/Radio-Buttons-for-Taxonomies#54]
I checked out the dev branch for WP5 compatibility and radios appear nicely for the chosen taxonomies.

Odd thing I noticed is, that I can't update the selected options after I saved the post. When I now edit a post, select different terms, and click save post, it jumps back to the old terms.

I'd expect the select option doesn't jump back and instead the newly selected terms get saved.

**Comment by helgatheviking** [comment]
First guess is this is related to #53

**Comment by leymannx** [comment]
Fixed via #53 I'd say.
