### ISSUE TITLE
[dev] Focused radio button styles underlapping wrapping container

### ISSUE THREAD

**Issue by leymannx** [helgatheviking/Radio-Buttons-for-Taxonomies#56]
Following https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues/53#issuecomment-486125368 I found the styles of a focused radio button looks a little bit odd as its overlapped by the wrapping container. Is this WP core interfering?

Adding screenshots for clarification:

![Screenshot 2019-04-24 10 32 39](https://user-images.githubusercontent.com/3585653/56645126-5be21880-667d-11e9-8ce5-36d078c4d342.png)
![Screenshot 2019-04-24 10 33 02](https://user-images.githubusercontent.com/3585653/56645137-600e3600-667d-11e9-8eb9-b31afb8e9c13.png)

**Comment by helgatheviking** [comment]
I don't think I'm adding any styles. But I did see this too. Doesn't seem
to be a problem for places where they are using radio in core.. like post
status.

**Comment by helgatheviking** [comment]
As far as I can tell, this is _also_ a problem in core. Therefore, I may not make any specific changes. If they add a little margin for checkboxes it should be ok in Radio buttons too. 

![image](https://user-images.githubusercontent.com/507025/56662576-4ac9f380-66df-11e9-8633-88e85d57e0bc.png)

**Comment by leymannx** [comment]
Ah yes, thanks a lot for confirming Kathy! I guess then we can close this issue as "works as designed" or "not our bug", I'd say.

**Comment by helgatheviking** [comment]
Agreed! Not my bug! :) Was just about to open an issue at Gutenberg, but it appears there [already is one](https://github.com/WordPress/gutenberg/issues/15045).

Let me try to get this packaged up and into the SVN repo.

**Comment by helgatheviking** [comment]
PS- thanks for all your help testing!

**Comment by leymannx** [comment]
You are welcome! Was really a pleasure to help you and watch the progress. Can you please ping me one last time as soon as the update is released on wordpress.org? I think I'm going to tweet about it and update my review on wordpress.org.

**Comment by helgatheviking** [comment]
@leymannx did my usual fight with SVN but 2.0 is now in the repo! will definitely appreciate you updating the review.

**Comment by leymannx** [comment]
Wow that was fast! I updated my review. ⭐️ ⭐️ ⭐️ ⭐️ ⭐️

**Comment by leymannx** [comment]
Do you know how to update the "Tested up to:" version as well? I think it should say 5.1.1

![Screenshot 2019-04-24 17 48 53](https://user-images.githubusercontent.com/3585653/56673980-84880380-66b9-11e9-966a-0d842d0f2fea.png)

**Comment by helgatheviking** [comment]
Yes, looks like I updated that in the plugin file, but forgot to update on
the readme.txt which is where the .org page pulls it's info from.

Updated!
