### ISSUE TITLE
Problem with Quick Edit

### ISSUE THREAD

**Issue by hkjersem** [helgatheviking/Radio-Buttons-for-Taxonomies#67]
Hi,

Thanks for your plugin, it's really nice. However, I have an issue with Quick Edit for posts. I'm using the plugin to enforce one category for every article, and it all works fine when creating and editing. But when I click Quick Edit, the current category is not selected and therefore reverts to the default category every time I save (unless I pick a category).

**Comment by helgatheviking** [comment]
Fairly certain this is fixed now
