### ISSUE TITLE
Broken settings link on plugin page (PR incoming)

### ISSUE THREAD

**Issue by casparhubinger** [helgatheviking/Radio-Buttons-for-Taxonomies#68]
https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/blob/ff9b83b2c1b9c73db6b2275019c21fb66bcf0fa4/radio-buttons-for-taxonomies.php#L299

`esc_html_e()` echoes the link which causes the string `Settings` to be printed somewhere above the plugin list table. To avoid this, the string should be returned. Incoming PR uses  `esc_html__()` instead.

**Comment by ocean90** [comment]
@helgatheviking Hi, any chance for a new release with this fix? Thank you!

**Comment by helgatheviking** [comment]
@ocean90 If I didn't mess up the SVN (always a chance!) I have just pushed this to the WordPress plugin repo.

**Comment by ocean90** [comment]
Thank you!
