### ISSUE TITLE
Option page - list more taxonomies by default

### ISSUE THREAD

**Issue by mathieuhays** [helgatheviking/Radio-Buttons-for-Taxonomies#70]
Hi,

I've got a few custom taxonomies set with `public = false` and `show_ui = true` which aren't displayed on the option page.

This is due to the fact that the query targets taxonomies with both `public = true` and `show_ui = true`.
https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/blob/aff74b05129b99c7ccc348801644d90532fe949e/radio-buttons-for-taxonomies.php#L334

Shouldn't the plugin only target taxonomies with `show_ui = true` and omit the `public` attribute as `show_ui` is the only relevant setting in this case if I'm not mistaken?

I'm aware I can load a custom set of taxonomies using the `radio_buttons_for_taxonomies_taxonomies` filter but I thought it could be a better default for the plugin.

Thanks for your help :-)

**Comment by helgatheviking** [comment]
Hi, thanks for reporting this. Sorry I missed it. Things have been weird and full disclosure, this isn't my top priority project.

You raise a good point though... I think we can do away with that `public` arg. Do you think we can also do away with the `_built_in` arg? If we only filter by `show_ui` then will we get all built in, public/not public taxonomies?

**Comment by mathieuhays** [comment]
No problem

> Do you think we can also do away with the `_built_in` arg?

Yes indeed. That way you'll only need one `get_taxonomies()` call.

> If we only filter by `show_ui` then will we get all built in, public/not public taxonomies?

Correct. We will only get the taxonomies that do display a meta box on the editor page.

Take care

**Comment by helgatheviking** [comment]
@mathieuhays any chance you can help test https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/tree/issues/70-show-ui ?
