### ISSUE TITLE
/js/dist/index.asset.php: No such file or directory

### ISSUE THREAD

**Issue by michelesalvador** [helgatheviking/Radio-Buttons-for-Taxonomies#75]
Just installed latest version 2.0.7 of Radio Buttons for Taxonomies.
Editing a post in the block editor, this warning appears on the background of the editor:
> Warning: include(C:\Users\Michele\Documents\Universita\online\app\public\wp-content\plugins\radio-buttons-for-taxonomies/js/dist/index.asset.php): failed to open stream: No such file or directory in C:\Users\Michele\Documents\Universita\online\app\public\wp-content\plugins\radio-buttons-for-taxonomies\radio-buttons-for-taxonomies.php on line 282

This happens on my local developing, I didn't try in production online.

**Comment by helgatheviking** [comment]
Thanks for reporting this

**Comment by helgatheviking** [comment]
In theory, 2.0.8 should fix this!
