### ISSUE TITLE
Fix CSS on tag taxonomies on block editor

### ISSUE THREAD

**Issue by papazetis** [helgatheviking/Radio-Buttons-for-Taxonomies#91]
On category taxonomies you have a margin-bottom on every element
`.editor-post-taxonomies__hierarchical-terms-choice {
    margin-bottom: 8px;
}`

Can you add the same css rule for tags as well, please?
`.editor-post-taxonomies__non-hierarchical-terms-choice {
    margin-bottom: 8px;
}`

**Comment by helgatheviking** [comment]
WordPress is responsible for that style rule, but I can see that by changing the class on the non-hierarchical items, it doesn't pick up that core style. I guess I can either give every radio button the hierarchical class... or find a way to load the CSS rule.
